# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

#controls When the action will run . This action runs every 6 hours

on:
  schedule:
       #every 6 hours
      - corn: "0 */6 * * * "

# This command allows us to run yhe action automatically from the action tab
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
 # This is workflow contains a single job called "build"
 build:
   #the type of runner that is jopb will run on
    runs-on: ubuntu-latest  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    #check repo under $GITHUB_WORKSHOP, so your job can access it
      -uses: action/checkout@v2

         #Generate the snake
         - uses: Platane /snk@master
           id: snake-gif
           with:
               github_user_name: naga100
               # these the next 2 lines generate files on branch called "output". This keeps the main branch from cluttering up.
               gif_out_path: dist/github-contribution-grid-snake.gif
               svg_out_path: dist/github-contribution-grid-snake.svg

        #show the status build. Makes it easier for debugging (if there's any issue).
        - run: git status

        # push the changes
        -name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

   - uses: crazy-max/ghaction-github-pages@2.1.3
     with:
     # the output branch we mentioned above
     target_branch: output
     build_dir: dist
    env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    